### ISSUE TITLE
[metal] ZINC GPU engine — macOS / Apple Silicon testers needed

### ISSUE THREAD

**Issue by bong-water-water-bong** [1bit-MONSTER/1bit-MONSTER#21]
## ZINC Metal Backend — Looking for macOS Testers

ZINC (our Zig LLM inference engine) has a **native Metal backend** — not MoltenVK, real Metal Shading Language compute shaders. It compiles on macOS today but needs testing on real Apple Silicon hardware.

### Build & Run

```bash
# Clone ZINC (separate repo, Apache 2.0)
git clone https://github.com/deepseek-ai/zinc.git
cd zinc

# Build with Metal backend (requires Zig 0.15.2+)
zig build -Doptimize=ReleaseFast -Dbackend=metal

# Download a GGUF model (e.g. Bonsai-1.7B-F16, LLaMA 3.2 1B, etc.)
# Run inference
./zig-out/bin/zinc -m model.gguf --prompt "Hello"
```

### What We Need to Know

| Question | Why |
|----------|-----|
| Does it compile on your macOS version? | Tested on Sequoia 15.x, needs broader coverage |
| What Apple Silicon chip? | M1/M2/M3/M4 — performance varies |
| tok/s decode speed? | Benchmark against llama.cpp on same model |
| Any crashes or shader compilation errors? | MSL shaders need real-hardware validation |
| Does the HTTP server work? | `zinc serve` starts and serves requests |

### Known Working Config

- **Apple M-series** (any)
- **macOS 15+** (Sequoia or later)
- **Zig 0.15.2+** — [Download zig](https://ziglang.org/download/)
- **GGUF models** — any quantization supported: f16, q4_k, q5_k, q6_k, q8_0

### Report Format

Please include:
```
Hardware: MacBook Pro M4 Max / 64GB
macOS: 15.3
Zig: 0.15.2
Model: Bonsai-1.7B-F16.gguf
zinc --version: v0.1.0-xxx

Build: succeeded / failed (paste errors)
Inference: 22.1 tok/s decode, 47ms/tok
Server: works / crashes on start
```

### Why This Matters

ZINC is the only open-source GPU inference engine with a native Metal backend. On Linux it beats llama.cpp on AMD RDNA4 across all published benchmarks. On macOS it should deliver competitive performance on Apple Silicon — but we need real hardware to confirm.

---

*Metal shaders. Zero ROCm. Zero CUDA. Runs on your Mac.*

**Comment by bong-water-water-bong** [comment]
## Status Update (Jul 10, 2026)

This issue remains open — we need **macOS + Apple Silicon** testers to validate ZINC's native Metal backend.

ZINC development continues in its own repo. The 1bit.systems packaging includes ZINC as the GPU backend option for macOS deployments.

Still needed:
- Test compilation on macOS 15+ (Sequoia or later) with Zig 0.15.2+
- Benchmark tok/s on M1/M2/M3/M4 hardware
- Validate Metal Shading Language compute shaders on real hardware
- Test the HTTP server (`zinc serve`) endpoint

See the issue body for the full test plan and report format.

**Comment by bong-water-water-bong** [comment]
This issue remains open for community testers. The macOS ZINC (Apple Silicon MLX) backend testing needs community volunteers with M-series Macs. If you have Apple Silicon hardware and can test the ZINC inference path, please report your results here — setup instructions are in `scripts/install-lemon-mlx.sh`.

**Comment by bong-water-water-bong** [comment]
Closing as not-actionable — community macOS/Apple Silicon testing remains open for volunteers.
