### ISSUE TITLE
engine/npu/build_npu.sh doesn't build cleanly: missing -fopenmp and aiebu library linking

### ISSUE THREAD

**Issue by bong-water-water-bong** [1bit-MONSTER/1bit-MONSTER#714]
## Description

While rebuilding \`npu_engine_universal\` from a clean checkout to verify a different fix, \`bash engine/npu/build_npu.sh\` fails at the link step (after fixing the separate compile error in #713):

\`\`\`
undefined reference to \`aiebu::aiebu_assembler::aiebu_assembler(...)\`
undefined reference to \`aiebu::aiebu_assembler::get_elf() const\`
undefined reference to \`omp_get_thread_num\`
\`\`\`

The source uses OpenMP (\`omp_get_thread_num\`, and the editor/LSP separately flags \`omp.h\` not found) and links against \`aiebu\`, but \`build_npu.sh\`'s \`CXXFLAGS\`/\`LIBS\` don't include \`-fopenmp\` or an aiebu library path/link flag.

A working \`npu_engine_universal\` binary does exist elsewhere on this box (a separately-built copy, not from this exact script invocation), so this is buildable with the right flags/environment — \`build_npu.sh\` as committed just doesn't carry them.

## Fix

Add \`-fopenmp\` to \`CXXFLAGS\` and the correct aiebu include/link flags to \`LIBS\` in \`engine/npu/build_npu.sh\`, or document the expected build environment (e.g. a sourced env script) if this script was never meant to be run standalone.

## Found via

Discovered while verifying the fix referenced in #711 (see that issue's comments) — a genuine, separate build-environment gap, not related to the correctness question under investigation there.

**Comment by bong-water-water-bong** [comment]
Fixed in #715
